function(clone_repo repo rel_path)
    set (PATH ${PROJECT_SOURCE_DIR}/${rel_path})
    if(NOT IS_DIRECTORY ${PROJECT_SOURCE_DIR}/${rel_path})
        if (IS_HTTPS)
            add_custom_command(TARGET CLONE_PROJECTS COMMAND git clone https://github.com/${repo} ${PATH})
        else()
            add_custom_command(TARGET CLONE_PROJECTS COMMAND git clone git@github.com:${repo} ${PATH})
        endif()
    endif()
endfunction()

clone_repo(lobovAuto/otus_hw6.git homework_6)
clone_repo(google/googletest.git gtest)
